### Variables
@baseUrl = http://localhost:8081/api/v1/users


##################################################
# CREATE OWNER - SUCCESS
##################################################

### Should create owner successfully
POST {{baseUrl}}/owners
Content-Type: application/json

{
  "name": "Juan",
  "lastName": "Vargas",
  "document": "123456789",
  "phone": "+573001234567",
  "birthDate": "1995-01-01",
  "email": "juan.vargas@test.com",
  "password": "Password123"
}


##################################################
# CREATE OWNER - REQUIRED FIELD VALIDATIONS
##################################################

### Should fail when name is empty
POST {{baseUrl}}/owners
Content-Type: application/json

{
  "name": "",
  "lastName": "Vargas",
  "document": "123456789",
  "phone": "+573001234567",
  "birthDate": "1995-01-01",
  "email": "juan.vargas@test.com",
  "password": "Password123"
}


### Should fail when last name is empty
POST {{baseUrl}}/owners
Content-Type: application/json

{
  "name": "Juan",
  "lastName": "",
  "document": "123456789",
  "phone": "+573001234567",
  "birthDate": "1995-01-01",
  "email": "juan.vargas@test.com",
  "password": "Password123"
}


### Should fail when document is empty
POST {{baseUrl}}/owners
Content-Type: application/json

{
  "name": "Juan",
  "lastName": "Vargas",
  "document": "",
  "phone": "+573001234567",
  "birthDate": "1995-01-01",
  "email": "juan.vargas@test.com",
  "password": "Password123"
}


### Should fail when phone is empty
POST {{baseUrl}}/owners
Content-Type: application/json

{
  "name": "Juan",
  "lastName": "Vargas",
  "document": "123456789",
  "phone": "",
  "birthDate": "1995-01-01",
  "email": "juan.vargas@test.com",
  "password": "Password123"
}


### Should fail when birth date is missing
POST {{baseUrl}}/owners
Content-Type: application/json

{
  "name": "Juan",
  "lastName": "Vargas",
  "document": "123456789",
  "phone": "+573001234567",
  "email": "juan.vargas@test.com",
  "password": "Password123"
}


### Should fail when email is empty
POST {{baseUrl}}/owners
Content-Type: application/json

{
  "name": "Juan",
  "lastName": "Vargas",
  "document": "123456789",
  "phone": "+573001234567",
  "birthDate": "1995-01-01",
  "email": "",
  "password": "Password123"
}


### Should fail when password is empty
POST {{baseUrl}}/owners
Content-Type: application/json

{
  "name": "Juan",
  "lastName": "Vargas",
  "document": "123456789",
  "phone": "+573001234567",
  "birthDate": "1995-01-01",
  "email": "juan.vargas@test.com",
  "password": ""
}



##################################################
# DOMAIN INVARIANTS
##################################################

### Should fail when document contains letters
POST {{baseUrl}}/owners
Content-Type: application/json

{
  "name": "Juan",
  "lastName": "Vargas",
  "document": "ABC123",
  "phone": "+573001234567",
  "birthDate": "1995-01-01",
  "email": "juan.vargas@test.com",
  "password": "Password123"
}


### Should fail when phone format is invalid
POST {{baseUrl}}/owners
Content-Type: application/json

{
  "name": "Juan",
  "lastName": "Vargas",
  "document": "123456789",
  "phone": "ABC123",
  "birthDate": "1995-01-01",
  "email": "juan.vargas@test.com",
  "password": "Password123"
}


### Should fail when phone exceeds maximum length
POST {{baseUrl}}/owners
Content-Type: application/json

{
  "name": "Juan",
  "lastName": "Vargas",
  "document": "123456789",
  "phone": "+57300123456789",
  "birthDate": "1995-01-01",
  "email": "juan.vargas@test.com",
  "password": "Password123"
}


### Should fail when email format is invalid
POST {{baseUrl}}/owners
Content-Type: application/json

{
  "name": "Juan",
  "lastName": "Vargas",
  "document": "123456789",
  "phone": "+573001234567",
  "birthDate": "1995-01-01",
  "email": "juan.vargas",
  "password": "Password123"
}


### Should fail when user is under age
POST {{baseUrl}}/owners
Content-Type: application/json

{
  "name": "Juan",
  "lastName": "Vargas",
  "document": "123456789",
  "phone": "+573001234567",
  "birthDate": "2010-01-01",
  "email": "juan.vargas@test.com",
  "password": "Password123"
}